---
- name: 设置主机名
  raw: hostnamectl set-hostname {{lb_name}} &&
       hostname {{lb_name}}

- name: 关闭firewalld
  service: name=firewalld state=stopped enabled=no

- name: 关闭selinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"

- name: 配置/etc/resolv.conf
  template: src=resolv.conf.j2 dest=/etc/resolv.conf

- name: 安装NGINX和Keepalived
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - epel-release
    - nginx
    - keepalived
    - iptables-services

- name: 配置HA
  template: 
    src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'nginx.conf.j2', dest: '/etc/nginx/nginx.conf' }
    - { src: 'keepalived.conf.j2', dest: '/etc/keepalived/keepalived.conf' }

- name: 启动HA
  systemd: name={{ item }} state=restarted enabled=yes
  with_items:
    - nginx
    - keepalived

- name: 配置iptables
  copy: src=iptables dest=/etc/sysconfig/iptables
  notify:
    restart iptables
