---
- name: 关闭firewalld
  service: name=firewalld state=stopped enabled=no
  
- name: 关闭selinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"
    
- name: 关闭swap分区
  replace:
    dest: /etc/fstab
    regexp: '(^.*swap.*$)'
    replace: '#\1'
    
- name: 即时生效
  shell: setenforce 0 ; swapoff -a
  
- name: 拷贝时区
  copy: src=/usr/share/zoneinfo/Asia/Shanghai dest=/etc/localtime

- name: 配置/etc/resolv.conf
  template: src=resolv.conf.j2 dest=/etc/resolv.conf

- name: 设置主机名
  raw: hostnamectl set-hostname {{host_name}} &&
       hostname {{host_name}}
  
- name: 添加hosts
  template: src=hosts.j2 dest=/etc/hosts
